services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: focusframe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: focusframe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge
